name: 'Continuous Integration'

on:
  create:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'

jobs:
  run:
    uses: "nucleos/actions/.github/workflows/continuous-integration.yml@main"
    with:
      PHP_EXTENSIONS: "mbstring"
      SYMFONY_KERNEL: "Nucleos\\MapsBundle\\Tests\\App\\AppKernel"
      SYMFONY_VERSIONS: "6.4,7.0"
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
